name: Makefile Basic Python 

on:
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "main","master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
 

    - name: Install dependencies
      run: make install 
 
    - name: Format
      run: make format 
      
    - name: Lint
      run: make lint 
      
    - name: Test 
      run: make test
      